# Generated by Django 4.2.2 on 2023-06-26 05:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.db import migrations, connection

def alter_table(apps, schema_editor):
    query ="ALTER TABLE AssetTypeModel ADD UNIQUE (Asset_Type);"
    cursor = connection.cursor()
    cursor.execute(query)
    cursor.close()
class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssetTypeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Asset_Type", models.TextField()),
                ("Asset_Description", models.TextField(max_length=500)),
                (
                    "Created_At",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 6, 26, 5, 7, 14, 62785)
                    ),
                ),
                (
                    "Updated_At",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 6, 26, 5, 7, 14, 62801)
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssetModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("AssetName", models.TextField()),
                ("AssetCode", models.TextField(default="0e6b4170-1b0d-44ca")),
                ("Active_Status", models.BooleanField(default=True)),
                (
                    "Created_At",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 6, 26, 5, 7, 14, 63410)
                    ),
                ),
                (
                    "Updated_At",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 6, 26, 5, 7, 14, 63422)
                    ),
                ),
                (
                    "AssetType",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Asset_App.assettypemodel",
                    ),
                ),
            ],
        ),
    ]
