# Generated by Django 4.2.2 on 2023-06-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Asset_App", "0018_alter_assetmodel_assetcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetmodel",
            name="AssetCode",
            field=models.UUIDField(
                default="df6b5174-4663-40f1-ae12-2680ef9ab3b7", editable=False
            ),
        ),
    ]
