# Generated by Django 4.2.2 on 2023-06-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Asset_App", "0019_alter_assetmodel_assetcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetmodel",
            name="AssetCode",
            field=models.UUIDField(
                default="77891016-8896-423c-9ea8-99807930ce63", editable=False
            ),
        ),
    ]
