# Generated by Django 4.2.2 on 2023-06-29 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Asset_App", "0022_alter_assetmodel_assetcode"),
    ]

    operations = []
