# Generated by Django 4.2.2 on 2023-06-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Asset_App", "0024_alter_assetmodel_assetcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetmodel",
            name="AssetCode",
            field=models.UUIDField(
                default="5b780474-9964-400f-8c81-3a5d39693ec6", editable=False
            ),
        ),
    ]
