# Generated by Django 4.2.2 on 2023-06-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Asset_App", "0025_alter_assetmodel_assetcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetmodel",
            name="AssetCode",
            field=models.UUIDField(
                default="4df65f2e-3cd4-4694-9ee9-f86f2e859f54", editable=False
            ),
        ),
    ]
