# Generated by Django 4.2.2 on 2023-06-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Asset_App", "0026_alter_assetmodel_assetcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetmodel",
            name="AssetCode",
            field=models.UUIDField(
                default="f0d95e35-1e14-4d7e-9ad1-8d051925340d",
                editable=False,
                unique=True,
            ),
        ),
    ]
