# Generated by Django 4.2.2 on 2023-06-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Asset_App", "0027_alter_assetmodel_assetcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetmodel",
            name="AssetCode",
            field=models.UUIDField(
                default="5653be56-a7ad-4a32-b263-9189f22e5015",
                editable=False,
                unique=True,
            ),
        ),
    ]
