# Generated by Django 4.2.2 on 2023-06-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Asset_App", "0029_alter_assetmodel_assetcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetmodel",
            name="AssetCode",
            field=models.TextField(
                default="9d52c6de-7bb3-4858-b7f5-72e3b307139e", editable=False
            ),
        ),
    ]
