# Generated by Django 4.2.2 on 2023-06-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Asset_App", "0030_alter_assetmodel_assetcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetmodel",
            name="AssetCode",
            field=models.TextField(default="9c1d28b7-87dc-431c-b1e4-7e9565f1c5cd"),
        ),
    ]
