# Generated by Django 4.2.2 on 2023-06-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Asset_App", "0031_alter_assetmodel_assetcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetmodel",
            name="AssetCode",
            field=models.TextField(default="<function uuid4 at 0x7f0b75fb1940>"),
        ),
    ]
